import React from 'react'
import Footer from '../../components/Footer'
import Header from '/src/components/Header'


const Terms = () => {
  return (
    <div className='pt-24'>
        <Header />
        <section className='px-4 pb-6 md:px-10 lg:px-24'>    
            <h1 className='text-green text-3xl text-center font-bold mt-4 mb-2'><strong>Yenreach Privacy Policy</strong></h1>
            <p className=''>This Privacy Policy describes our policies on the collection, use, and disclosure of information about you in connection and regarding your use of our services, including those offered through our website and communication channels (e.g., emails, phone calls, and texts). The terms “we”, “us”, and “Yenreach” refer to:</p>
            <p className=''>(i) Yenreach, a Nigerian business listing and advertisement platform headquartered in Yenagoa, Bayelsa State. By agreeing to Yenreach’s Privacy Policy, you consent to our collection, use, and disclosure of information about you as described in this Privacy Policy.</p>
        </section>
        <div className="pl-4 md:pl-8">
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>1. INFORMATION WE COLLECT AND HOW WE USE IT</h3>
                <p>We may collect, transmit, and store information about you in connection with your use of the Service, including any information you send to us or through our Service. We use that information to provide the Service’s functionality, fulfill your requests, improve the Service’s quality, engage in research and analysis relating to the Service, personalize your experience, track usage of the Service, provide feedback to third party businesses that are listed on the Service, display relevant advertising, market the Service, provide customer support, message you, back up our systems, allow for disaster recovery, enhance the security of the Service, and comply with legal obligations. Even when we do not retain such information, it still must be transmitted to our servers initially and stored long enough to process. Please note:</p>
                <ol className='pl-8'>
                    <li className='mb-2'><span className='font-semibold'> A. </span> When you create a Yenreach account, we store and use the information you provide during that process, such as the first and last name you enter, email address, physical address, and any other information you may provide during the account creation process, such as gender, phone number, or birth date. We may publicly display the first name and last initial that you provide, as well as any photograph or other content you submit through the account creation process, as part of your account profile. We also store and use any preferences you provide to personalize your user experience, including dining and activity preferences. You can later modify some of the account information you provide through your user dashboard or console. If you believe that someone has created an unauthorized account using your personal information, you can request its removal by flagging it.</li>
                    <li className='mb-2'><span className='font-semibold'>B. Public Content:</span> 
                    Your contributions to the Service are intended for public consumption and are therefore viewable by the public, including your photographs, ratings, reviews, tips, lists, Collections, and compliments, you can ask for the Community posts, and edit the business page information. Your account profile (e.g., first name, last name, city, neighborhood, the month and year you created your Yenreach account, profile photographs) is also intended for public consumption, as is some of your other activities through the Service, like how you vote on other people’s contributions (e.g., useful, funny, cool, helpful, or not helpful), which contributions you like, which contributions or users you follow, and which businesses you follow or bookmark. You can limit the public nature of some of these activities on your dashboard or console.
                    </li>
                    <li className='mb-2'><span className='font-semibold'>C. Contacts: </span> You can invite others to join or become your friend on Yenreach by providing us with their contact information, or by allowing us to access contacts from your computer, mobile device, or third-party sites to select which individuals you want to invite. If you allow us to access your contacts, we will transmit information about your contacts to our servers long enough to process your invitations.</li>
                    <li className='mb-2'><span className='font-semibold'>D. Communications: </span> When you sign up for an account or use certain features, you are opting to receive messages from other users, businesses, and Yenreach. You can manage some of your messaging preferences through your Yenreach dashboard or console but note that you cannot opt out of receiving certain administrative, transactional, or legal messages from Yenreach. For example, if you make a reservation, order food, place yourself on a waitlist, or request a quote from a business through the Service, we may send you messages about your transaction using the contact information you provide, including through automated (SMS) text messages to your phone number. We may also track your actions in response to the messages you receive from us or through the Service, such as whether you deleted, opened, or forwarded such messages, and share that information with other parties to your messages (for example, to let them know if you have viewed their message). When a user requests a quote or similar information from multiple businesses through the Service, we may disclose to those businesses information about the status of the user’s requests, such as whether any business has responded to the request, the type of response provided (for example, a quote or a request for more information), and whether the user has responded to any business’s reply. If you exchange messages with others through the Service, we may store them in order to process and deliver them, and/or allow you to manage them, and we may review and disclose them in connection with investigations related to use of the Service, as well as our efforts to improve the Service. We may not deliver messages that we believe are objectionable, such as spam messages, fraudulent solicitations, or requests to exchange reviews for compensation. If you send or receive messages through the Service via (SMS) text message, we may log phone numbers, phone carriers, and the date and time that the messages were processed. We may also store information that you provide through communications to us, including from phone calls, letters, emails and other electronic messages, or in person. If you are a representative of a business listed on Yenreach, or use a phone number associated now or previously with such a business, we may contact you, including by phone, text or email, using the contact information you provide us, make publicly available, or that we have on record for your business. Our communications with you, including phone calls, may be monitored and recorded for security and quality purposes.</li>
                    <li className='mb-2'><span className='font-semibold'>E. Transactions: </span> If you initiate a transaction through the Service, such as a reservation or purchase, we will collect and store information you provide associated with your transaction, such as your name, phone number, address, email, and payment information, as well as any other information you provide, in order to process your transaction, send communications about the transaction to you, and facilitate future transactions. This information may be shared with third parties, and third parties may share such information with us, for the same purposes. When you submit credit card numbers and other sensitive payment information, that information is encrypted using industry standard technology. If you write reviews about businesses with which you transact through the Service, we may publicly display the fact that you transacted with those businesses in connection with such reviews. For example, if you make a dining reservation through the Service and later write a review about your experience, we may publicly display the fact that you made your reservation through the Service.</li>
                    
                    <li className='mb-2'><span className='font-semibold'>F. Activity: </span> : We store information about your use of the Service, such as your search activity, the pages you view, the date and time of your visits, businesses you call from our system or on our mobile applications, and reservations, purchases, or transactions you make through the Service. We also store information that your computer or mobile device may provide to us in connection with your use of the Service, such as your browser type, type of computer or mobile device, browser language, IP address, WiFi information such as SSID, mobile carrier, phone number, unique device identifier, advertising identifier, location (including geolocation, beacon based location, and GPS location), and requested and referring URLs and mobile applications. We may also receive and store your location whenever our mobile applications are running, including when running in the background, if you enable our mobile apps to access such information in the course of using the Service. You may be able to limit, restrict, allow or disallow our use of certain location data through your device or browser settings, for example by adjusting the settings for our applications in iOS or Android privacy settings.</li>
                    <li className='mb-2'><span className='font-semibold'>G. Professional Information: </span> If you represent a business on Yenreach, we may collect and display information related to your business activities, such as a business name that may incorporate your name, or a publicly available business address that is also used as a home address. We will also collect and display information about your professional background that you choose to share with us through the Service, such as information about your professional licenses or certifications, or your professional history or specialties. H. Legal Basis for Processing: As a business operating in Nigeria, our legal basis for collecting and using the information described above will depend on the specific information concerned and the context in which we collect it. We, however, will normally collect personal information from you only where we have your consent to do so, where we need the personal information to perform a contract with you, or where the processing is in our legitimate interests and not overridden by your data protection interests or fundamental rights and freedoms. In some cases, we may also have a legal obligation to collect personal information from you or may otherwise need the personal information to protect your vital interests or those of another person (for instance, to prevent, investigate, or identify possible illicit dealing in connection with the Service or to comply with legal obligations). If we ask you to provide personal information to comply with a legal requirement or to perform a contract with you, we will make this clear at the relevant time and advise you whether the provision of your personal information is mandatory or not (as well as of the possible consequences if you do not provide your personal information). If we collect and use your personal information in reliance on our legitimate interests (or those of any third party), this interest will typically be to operate our Services, communicate with you in relation to our Services, or for our other legitimate commercial interests, for instance, when responding to your queries, to analyze and improve our platform, engage in marketing, or for the purposes of detecting or preventing fraud, and to comply with extant laws operational in the cyberspace. If you have questions about or need further information concerning the legal basis on which we collect and use your personal information, please contact us at the address listed below in the “Contact Us” section.</li>
                </ol>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>2. COOKIES</h3>
                <p>
                We, and third parties with whom we partner, may use cookies, web beacons, tags, scripts, locally shared objects such as HTML5 and Flash (sometimes called “flash cookies”), advertising identifiers (including mobile identifiers such as Apple’s Identifier for Advertisers (“IDFA”) or Google’s Advertising ID (“GAID”)) and similar technology (“Cookies”) in connection with your use of the Service, third party websites, and mobile applications. Cookies may contain unique identifiers, and reside, among other places, on your computer or mobile device, in emails we send to you, and on our web pages. Cookies may transmit information about you and your use of the Service, such as your browser type, search preferences, IP address, data relating to advertisements that have been displayed to you or that you have interacted with, and the date and time of your use. Cookies may be persistent or stored only during an individual session. Manage cookies You can set some Cookies preferences through your device or browser settings, but doing so may affect the functionality of the Service. The method for disabling Cookies may vary by device and browser, but can usually be found in your device or browser preferences or security settings. For example, iOS and Android devices each have settings which are designed to limit forms of ad tracking. Please note that changing any of these settings does not prevent the display of certain advertisements to you.
                </p>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>3. THIRD PARTIES</h3>
                <p>Third parties may receive information about you as follows:</p>
                <ol className='pl-8'>
                    <li className='mb-2'>
                        <span className='font-bold'>A. Advertisers:</span>
                        We allow third parties to use Cookies through the Service to collect the same type of information for the same purposes as we do. In so doing, we adhere to the Digital Advertising Alliance’s Self-Regulatory Principles for Online Behavioral Advertising. Third parties may be able to associate the information they collect with other information they have about you from other sources. We do not necessarily have access to or control over the Cookies they use, but you may be able to opt out of some of their practices by visiting the following links: Network Advertising Initiative, Omniture and Digital Advertising Alliance. Please note that opting out does not prevent the display of all advertisements to you. We may also share some non-identifiable, de-identified or aggregated information from or about you, such as location information, with third parties in connection with advertising programs and data analytics.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>B. Content Partners:</span>
                        We allow third party partners to use and display some of the public content available through the Service, such as your photos, reviews, and other information listed under “Public Content” in Section 1 above
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>C. Service Providers:</span>
                        We rely on third party service providers to support or provide services for us in connection with your use of the Service, such as communications and hosting, security and fraud prevention, technical and customer support, tracking and reporting usage of the Service, quality assurance testing, payment processing, marketing, and other functions. We share information from or about you with these third-party providers so that they can perform their services or complete your requests. For example, we may share your advertising identifiers (e.g., your IDFA, GAID, or a cryptographic hash of your email address) with third party service providers that help us facilitate Yenreach’s advertising programs and measure and report their effectiveness, including with third parties that help determine the efficacy of Yenreach’s advertising programs by combining information they receive about you from other sources than the Service of Yenreach. You may be able to limit our access to some of these information through your business dashboard or console. Yenreach’s third party service providers may likewise share information with us that they obtain from or about you in connection with providing their services or completing your requests.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>D. Aggregate or Anonymous Information:</span>
                        We share user information in the aggregate with third parties, such as businesses that are listed on Yenreach and content distributors. For example, we disclose the number of users that have been exposed to or interacted with advertisements, or that we believe visited the physical location of a particular business.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>E. Business Transfers:</span>
                        We share information from or about you with our parent companies, subsidiaries, joint ventures, or other companies under common control, and require them to also honor this Privacy Policy. If another company acquires Yenreach, or all or substantially all our assets, that company will possess the same information, and will collect, use, and disclose the information only as described in this Privacy Policy.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>F. Businesses on Yenreach:</span>
                        We may share information from or about you (such as your city, and if you provide it, your age and gender), and your use of the Service (such as which businesses you bookmark or call, or if you visit a business’s URL) with businesses on Yenreach. You may adjust your account settings to increase or decrease the amount of information we share. Keep in mind that businesses can also view your public activity and posts, and may receive information from or about you when you transact or communicate with them, through Yenreach or otherwise, regardless of your settings (see Section 1 above). Additionally, if you make a phone call to a business through or in connection with your use of the Service, we may share information about your call with the business that the business would have received had you called them directly, such as the date and time of your call and your phone number. You may be able to limit our ability to collect and share your phone number through your phone settings or phone service provider.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>G. Investigations and Legal Disclosures:</span>
                        We may investigate and disclose information from or about you if we have in good faith belief that such investigation or disclosure:
                        <ol className='pl-4'>
                            <li>
                                <span className='font-bold'>(a) </span>
                                is reasonably necessary to comply with legal process and law enforcement instructions and orders, such as a search warrant, subpoena, statute, judicial proceeding, or other legal process or law enforcement requests served on us;
                            </li>
                            <li>
                                <span className='font-bold'>(b) </span>
                                is helpful to prevent, investigate, or identify possible wrongdoing in connection with the Service; or
                            </li>
                            <li>
                                <span className='font-bold'>(c) </span>
                                protects our rights, reputation, property, or that of our users, affiliates, or the public, such as disclosures in connection with Yenreach’s Consumer Alerts program. If you flag or otherwise complain to us about content through the Service, we may share the substance of your complaint with the contributor of that content in order to provide an opportunity for the contributor to respond.
                            </li>
                        </ol>
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>H. Links:</span>
                        The Service may link to third party-controlled websites, like a business’s URL. Except as set forth herein, we do not share your personal information with them, and are not responsible for their privacy policy practices.
                    </li>
                    <li className='mb-2'>
                        <span className='font-bold'>I. Third Party Integrations:</span>
                        If you sign up for, or log into, Yenreach using a third party service like Facebook or Google, or link your Yenreach account to your account with a third party service like Facebook, Instagram or Twitter, we may receive information about you from such third party service. If you post content to a third party service through our Service, that third party service will also receive that content, which will be visible to anyone that has access to it through that third party service. Some of our web pages utilize framing techniques to serve content to you from our third party partners, while preserving the look and feel of the Service. In such cases, please note that the information you provide may be transmitted directly to the identified third party partner. If you interact with businesses through Yenreach, they will receive whatever information you choose to share with them, for example contact information you share through direct messages to the business or your phone number if you call the business.
                    </li>
                </ol>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>4. CONTROLLING YOUR PERSONAL DATA</h3>
                <p>Other users may be able to identify you, or associate you with your account, if you include personal information in the content you post publicly. You can reduce the risk of being personally identified by using the Service pseudonymously, though doing so could detract from the credibility of your contributions to the Service. Yenreach users can also use the Find Friends feature to find one another based on their names or email addresses (you can limit your visibility for this feature in your account settings). Please also note that the messages you send or receive using the Service are only private to the extent that both you and the recipient(s) of your messages keep them private. For example, if you send a message to another user, that user may choose to publicly post it. We may access, review, and disclose such messages in connection with investigations related to use of the Service, as well as our efforts to improve the Service</p>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>5. DATA RETENTION AND ACCOUNT TERMINATION</h3>
                <p>You can close your account by clicking here. We will remove certain public posts from view and/or dissociate them from your account profile, but we may retain information about you for the purposes authorized under this Privacy Policy unless prohibited by law. For example, we may retain information to prevent, investigate, or identify possible wrongdoing in connection with the Service or to comply with legal obligations. We may also maintain residual copies of your personal information in our backup systems. Please note that businesses cannot remove their business pages, ratings, or reviews by closing their accounts.</p>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>6. CHILDREN</h3>
                <p className='mb-5'>The Service is intended for general audiences and is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that a child has provided us with personal information without parental consent, please send us a message on the Contact Us section. If we become aware that a child under 13 has provided us with personal information without parental consent, we take steps to remove such information and terminate the child’s account.</p>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>7. SECURITY</h3>
                <p>We use various safeguards to protect the personal information submitted to us, both during transmission and after we receive it. However, no method of transmission over the Internet or via mobile device, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>
            </section>
            <section className='mb-12 px-4 md:px-10 lg:px-24'>
                <h3 className='font-bold mb-3'>8. MODIFICATIONS TO THIS PRIVACY POLICY</h3>
                <p>We may revise this Privacy Policy from time to time. The most current version of the Privacy Policy will govern our collection, use, and disclosure of information about you. If we make material changes to this Privacy Policy, we will notify you by email or by posting a notice on the Service prior to or on the effective date of the changes. By continuing to access or use the Service after those changes become effective, you acknowledge the revised Privacy Policy:</p>
            </section>
        </div>
        <Footer />
    </div>
  )
}

export default Terms